### ISSUE TITLE
no working plugin on petadactyl lastest

### ISSUE THREAD

**Issue by ghost** [gwash/penta-sessions#5]
where I can find plugin start logs? Js and unix console did not show anything...
Seems like we need JSON information instead of XML, like in other lastest plugins?

**Comment by gwash** [comment]
Yes, that's the problem, I got quite a few other plugins to convert, will get to it soon, thanks for reporting.

**Comment by ghost** [comment]
If you explain me how to debug plugin like this, then I can help you to fix it

**Comment by gwash** [comment]
Well, the issue is pretty simple to fix, just time consuming. You could look at how the 'INFO' variable is constructed in the official plugins, and try to convert the E4X XML syntax into JSON in this plugin. Using RegEx could help speed the process a bit, but you really have to pay close attention to what's getting replaced, making sure it's viable JSON (hint: use the 'c' switch with vim's :s cmd).

Good luck, I really appreciate you trying to help.

**Comment by ghost** [comment]
ok, thanks. Also helpful tool here: http://www.utilities-online.info/xmltojson/
But major issue for me - plugin log and errors not shown in browser console 
maybe   'browser.dom.window.dump.enabled'? i'll try today...

**Comment by ghost** [comment]
part of the original xml been converted to json, and now our plugin can start and create commands.
One thing fails now - session completion, and I can't debug this, because 'browser.dom.window.dump.enabled' didn't help with console.log visibility

**Comment by ghost** [comment]
gwash: can you explain me how to turn debug mode on?

**Comment by gwash** [comment]
Hi ghost, I really appreciate your effort, but I can't apply that patch because it removes documentation altogether, I'm almost done converting the E4X XML in this plugin, will be done in an hour or so.

Thanks again.
